const mockEvents = {
    city: {
        id: 1007700,
        city: 'München',
        lat: 48.14,
        lon: 11.58,
        state: '',
        country: 'de',
        zip: 'meetup3',
        member_count: 1257
    },
    events: [
        {
            created: 1593547541000,
            duration: 3600000,
            id: 'lxfwtrybclblc',
            name: '+Free Meditation & Yoga - CENTER RE-OPENED!  just show up – we start at 19:30h',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1598635800000,
            local_date: '2020-08-28',
            local_time: '19:30',
            updated: 1593547541000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 10,
            venue: {
                id: 26353279,
                name: 'Sahaja Yoga Zentrum München',
                lat: 48.13127899169922,
                lon: 11.589085578918457,
                repinned: true,
                address_1: 'Am Lilienberg 2a',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1405527637000,
                name: 'Free Meditation & Yoga – in Munich/München (4.400+ members)',
                id: 15760412,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Free-Meditation-Yoga-Munich',
                who: 'Meditators',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/lxfwtrybclblc/',
            description: '<p>STARTET WIEDER VORORT als Präsenz-Meditation !</p> <p>Für Anfänger &amp; Fortgeschrittene, Einstieg jederzeit möglich</p> <p>With Sahaja Yoga Meditation we generally sit on chairs to achieve Yoga, effortlessly, spontaneously. As such no Asanas (exercises) are required, no mat or special clothing. We are all volunteers of a Charity organisation and have many years of experience in offering free Sahaja Yoga Meditation classes. The classes are designed to help those attending get into a genuine meditative state, which can be felt tangibly. It is quite effortless and spontaneous. The free classes feature introductory talks, video\'s, practical workshops and general question and answer opportunities, making them perfect for seekers trying to establish a state of yoga, and they are available throughout Germany.</p> <p>The idea is that you don\'t do yoga - you Achieve Yoga!</p> <p>Sahaja Yoga Meditation is a simple, time-honored technique. It helps those who enjoy it, reduce stress and increase wellness. It brings better focus and helps people become more centered and better balanced. Anyone can do it. Founded by Shri Mataji Nirmala Devi, Sahaja Yoga Meditation is a world wide movement for peace and self awakening.</p> <p>All the meetings and classes are free of any charge. Each week we go through simple meditation techniques, often with guided meditations to help reduce stress and achieve the peace of true meditation. We share tips on how to help stay in balance during the day and how to meditate at home. The meditation is based on connecting with the inner chakras (energy centres) and balancing the subtle body. The tradition and aims of meditation are explained which in essence is to be in the present with no mental activity or thoughts about the past or the future.</p> <p>Occasionally there are 1 day retreats to help those interested, deepen their individual experience and hear advice and tips from those who have been practicing for some time. It’s ultimately all about getting into ‘thoughtless awareness’, a natural state of being.</p> <p>Most of the times courses are held in German Language, but we do speak english also, some of us can also speak other languages. So don´t be shy to ask.</p> <p>Occasionally there are 1 day retreats to help those interested, deepen their individual experience and hear advice and tips from those who have been practicing for some time. It’s ultimately all about getting into ‘thoughtless awareness’, a natural state of being.</p> <p>**** ENGLISH ****</p> <p>Entdecke die Kraft die in Dir steckt!</p> <p>Herzlich Willkommen zu unseren kostenfreien Treffen. In der Sahaja Yoga Meditation sitzen wir \'normal\' auf Stühlen, um ohne Anstrengung und spontan das Yoga zu erreichen. Es sind keine Matten oder spezielle Kleidung notwendig.</p> <p>Die Kursleiter (Info:[masked]) sind alle ehrenamtlich für den gemeinnützigen Verein Sahaja Yoga e.V. tätig und haben mehrere Jahre Erfahrung in Sahaja Yoga Meditationskursen.</p> <p>Die Kurse sollen den Teilnehmern helfen in einen wirklichen meditativen Zustand zu kommen, der spürbar wahrgenommen werden kann. Es ist sehr spontan und ohne Anstrengung. Die Kurse beinhalten - neben einer geführten Gruppenmeditation - einführende Erklärungen, Videos, Workshops und Gelegenheiten für allgemeine Fragen und Antworten; sie sind perfekt für Sucher die den Zustand des Yoga (= gedankenfreies Bewusstsein / Tao / Sartory / Selbstverwirklichung ...) erreichen wollen.</p> <p>The idea is that you don\'t do yoga - YOU ACHIEVE YOGA!</p> <p>Die Kurse finden in der Regel in deutscher Sprache statt. Bei Bedarf können wir englisch - teilweise auch andere Sprachen.</p> <p>Spontanes Kommen ist möglich, für uns wäre es zum planen gut, wenn ihr hier euer Kommen anmelden würdet.</p> <p>**** Über unser subtiles Sytem ****</p> <p>In jedem Menschen ist ein subtiles System aus Energiezentren (Chakren) und Kanälen (Nadis) angelegt. Es beeinflusst unser körperliches, emotionales, seelisches und geistiges Wohlbefinden, also alle Aspekte unseres Seins. Jedes Chakra ist mit bestimmten menschlichen Eigenschaften und Fähigkeiten verbunden.</p> <p>Durch die Meditation in Sahaja Yoga wird eine in uns schlafende Energie (Kundalini) erweckt. Diese mütterliche Kraft reinigt unsere Chakren und löst Blockaden. Unsere Stärken werden immer stärker und unsere Schwächen werden immer schwächer. Sahaja Yoga ist eine einfache, leicht zu erlernende Meditation. Sie hilft uns, zu entspannen, uns gut zu fühlen und gibt uns unsere innere Balance.</p> <p>Im ersten Satz der UNESCO-Verfassung steht: „Da Kriege im Geist der Menschen entstehen, muss auch der Frieden im Geist der Menschen verankert werden.“ Deshalb ist Sahaja Yoga ein Partner des UNESCO Center for Peace.</p> <p>Die Wechselwirkung zwischen Geist und Körper wird immer mehr erforscht. Wissenschaftliche Studien zeigen, dass regelmäßige Meditation die Gesundheit verbessert. Zum Beispiel gibt es positive Effekte bei Burnout, Depression, Schlaflosigkeit, ADHS, Asthma und bei vielen anderen Problemen. Ängste werden reduziert, die Konzentration gesteigert und die Lebensfreude erhöht.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1595333312000,
            duration: 9000000,
            id: '272058870',
            name: 'DATAMADNESS MUNICH #1',
            rsvp_limit: 50,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1600360200000,
            local_date: '2020-09-17',
            local_time: '18:30',
            updated: 1597311924000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 22,
            venue: {
                id: 26968018,
                name: 'Sendlinger Str. 7',
                lat: 48.13581085205078,
                lon: 11.572131156921387,
                repinned: true,
                address_1: 'Sendlinger Str. 7',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1594983403000,
                name: 'DATAMADNESS MUNICH',
                id: 33975811,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'datamadness-munich',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/datamadness-munich/events/272058870/',
            description: '<p>topics: data science, product management, r, dashboards</p> <p># DATAMADNESS MUNICH #1 (September)</p> <p>* The Power of Data Product Management (Robert Keil)<br/>* Data Science MVPs with R Shiny (Sarah Stemmler)</p> <p>This event will be in English.</p> <p>Space is limited, please do register for a free ticket.</p> <p>We look forward to seeing you!</p> <p>## Health &amp; Safety Guidelines</p> <p>We hope to make this an offline event but amidst the current development of the pandemic, we really depend on your support. We will share the health and safety guidelines for our event here soon and expect all attendees to follow the instructions. Thanks for your cooperation!</p> <p>## Agenda</p> <p>18:00 – Doors open.</p> <p>18:30 – Welcome.</p> <p>18:45 – The Power of Data Product Management.</p> <p>19:30 – Break with pizza and cold drinks.</p> <p>20:00 – Data Science MVPs with R Shiny.</p> <p>20:45 – Open mic.</p> <p>21:00 – End.</p> <p>## Location</p> <p>The event will take place at the Usercentrics office in the heart of Munich. We will put up signs so you can\'t miss us.</p> <p>## Open mic</p> <p>The end of the event is dedicated to our attendees who want to share something they care about with the community. Any content is welcome, as long as it fits in three minutes and does not advertise paid products or services. If you want to reserve a spot, please reach out.</p> <p>## Acknowledgement</p> <p>Thanks a lot to our speakers Robert and Sarah!</p> <p>Also a big thank you to our sponsors:</p> <p>* Instaffo, for supporting the organization.<br/>* Usercentrics, for hosting the event.</p> <p>## Contact</p> <p>If you have any questions or suggestions, please feel free to contact us via:</p> <p>* Meetup<br/>* Telegram: <a href=\'https://t.me/joinchat/Lk5_ABrLl6xQiKXhBOI67w\' class=\'linkified\'>https://t.me/joinchat/Lk5_ABrLl6xQiKXhBOI67w</a></p> ',
            visibility: 'public',
            pro_is_email_shared: false,
            member_pay_fee: false
        },
        {
            created: 1591348394000,
            duration: 385200000,
            id: '271099242',
            name: 'International JavaScript Conference Munich 2020 - The Hybrid Conference',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1603695600000,
            local_date: '2020-10-26',
            local_time: '08:00',
            updated: 1597742159000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 13,
            venue: {
                id: 26495814,
                name: 'Holiday Inn München - Stadtzentrum',
                lat: 48.13063049316406,
                lon: 11.589532852172852,
                repinned: true,
                address_1: 'Hochstraße 3',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1497515784000,
                name: 'International JavaScript Conference',
                id: 24474394,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'International-JavaScript-Conference',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/International-JavaScript-Conference/events/271099242/',
            description: '<p>Every year in October, International JavaScript Conference Munich is where seasoned experts get together to discuss methods, libraries, services, models and algorithms to use. Keeping the current situation in mind, we announce that iJS Munich 2020 will be a Hybrid Conference - attend the conference on site or remotely from your home or office.</p> <p>We are looking forward to meeting you this year as well!</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1562750055000,
            duration: 10800000,
            id: 'tkqsdrybcmbmb',
            name: 'Designer-Stammtisch',
            rsvp_limit: 35,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1599670800000,
            local_date: '2020-09-09',
            local_time: '19:00',
            updated: 1562750055000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 3,
            venue: {
                id: 26506448,
                name: 'Cafe Zeitgeist',
                lat: 48.15114212036133,
                lon: 11.576687812805176,
                repinned: false,
                address_1: 'Türkenstraße 74',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1444668795000,
                name: 'Münchner Designer-Stammtisch',
                id: 19020346,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Designer-Stammtisch',
                who: 'Designer',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Designer-Stammtisch/events/tkqsdrybcmbmb/',
            description: '<p>Liebe DesignerInnen,</p> <p>wir treffen uns jeden 2. Mittwoch im Monat um 19:00 Uhr in (neu:) Zeitgeist in der Türkenstraße.</p> <p>Bringt eure Erfolge, neusten Projekte oder auch kleinen Problemchen mit und teilt sie mit anderen Designern bei einem entspannten Abendessen.</p> <p>Wir freuen uns auf neue Designer und alte Bekannte, und auf einen gemütlichen Abend mit Designer-Kaltsch-und-Tratsch.</p> <p>Lieben Gruß, Ben</p> <p>ps: für alle die gerne länger unterwegs sind finden wir auch diesmal bestimmt wieder eine Location.</p> <p>pps: We mostly chat in German, but English will work just find as well.</p> ',
            how_to_find_us: 'Fragt nach dem Designerstammtisch dort! *** Please ask for the Designerstammtisch there!',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1594142093000,
            duration: 7200000,
            id: '271775637',
            name: 'Beer, Brotzeit and IoT @ Concept Reply',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1603384200000,
            local_date: '2020-10-22',
            local_time: '18:30',
            updated: 1598025454000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 36,
            venue: {
                id: 26066109,
                name: 'Luise-Ullrich-Straße 14',
                lat: 48.14474868774414,
                lon: 11.538175582885742,
                repinned: true,
                address_1: 'Luise-Ullrich-Straße 14',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1508251656000,
                name: 'München IoT Meetup',
                id: 26294946,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Muenchen-IoT-Meetup',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Muenchen-IoT-Meetup/events/271775637/',
            description: '<p>We will also broadcast the event live for people who would rather stay at home on YouTube: <a href=\'https://youtu.be/JYnYmkfO4PU\' class=\'embedded\'>https://youtu.be/JYnYmkfO4PU</a></p> <p>How to find the new venue:<br/>Enter the Nove Building from Luise-Ullrich-Straße 14 (you should see a statue and a restaurant outside). On entering you will see the main reception in front of you with a security guard, two lifts to the left and a model of the building to the right. Walk toward the reception, take the first left and walk toward the other two lifts in front of you. The first door on the left with the Reply logo leads to the Meetup on the *ground floor*.</p> <p>Agenda:</p> <p>18:30: Brotzeit<br/>19:00: Markus Jung (OSRAM) - The OSRAM portfolio of IoT connected products<br/>19:30: Christopher Ziegler (Actyx.io) - The modern way of automating and digitizing factories<br/>20:00: Networking</p> <p>Food and drink served throughout. All presentations in English.</p> ',
            how_to_find_us: 'Public transport: Donnersbergerstraße | 250m (Tram 16, 17) Donnersbergerbrücke | 450m (Suburban train towards Pasing, Bus 53 & 63) Address: Concept Reply (part of REPLY AG) Nove building Luise-Ullrich-Straße 14 80636 München Reply Büro beim EG',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1592331633000,
            duration: 5400000,
            id: 'zsxjtrybclbpc',
            name: 'Young Generation - Free Meditation - Sahaja Yoga Center RE-OPENED!',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1598895000000,
            local_date: '2020-08-31',
            local_time: '19:30',
            updated: 1592331633000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 5,
            venue: {
                id: 26353279,
                name: 'Sahaja Yoga Zentrum München',
                lat: 48.13126754760742,
                lon: 11.589075088500977,
                repinned: true,
                address_1: 'Am Lilienberg 2a',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1405527637000,
                name: 'Free Meditation & Yoga – in Munich/München (4.400+ members)',
                id: 15760412,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Free-Meditation-Yoga-Munich',
                who: 'Meditators',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/zsxjtrybclbpc/',
            description: '<p>Sahaja Yoga Center RE-OPENED!</p> <p>Free Meditation class for BEGINNERS &amp; ADVANCED !</p> <p>A Global initiative to change the world by changing ourselves.</p> <p>Info: mobile/whatsapp: [masked] (Ganesh)</p> <p>Video: <a href=\'https://www.youtube.com/watch?v=DrCcHm_M16Y&amp;list=PL11600E36E6E9E4AC\' class=\'embedded\'>https://www.youtube.com/watch?v=DrCcHm_M16Y&amp;list=PL11600E36E6E9E4AC</a></p> <p>CoolCheck-Website (<a href=\'http://coolcheck.org/\' class=\'linkified\'>http://coolcheck.org/</a>)</p> <p>Life only gets better. You’re about to start an amazing journey.</p> <p>However, it is special because it has the power to completely and totally relax your mind and body while energizing it, leaving you in a state where you are able to do anything and everything.<br/>Now we get down to the technicalities. The first step to achieving a state of meditation is simply desire; you have to want it. For your first meditation, it is best to find a quiet place where you can sit comfortably. Take your shoes, glasses, or any extra items off; basically get ready to relax.<br/>Now you know the body is made of three channels and 7 energy centers. An imbalance in any of these is due to the life we lead. So the first thing we shall do is to cleanse these Centers.</p> ',
            how_to_find_us: 'S-Bahn Rosenheimerplatz, gegenüber Gasteig',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1581340324000,
            duration: 32400000,
            id: '268602441',
            name: 'Hack&Jump - München 2020',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1604574000000,
            local_date: '2020-11-05',
            local_time: '12:00',
            updated: 1581340324000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 7,
            venue: {
                id: 26120186,
                name: 'HANS IM GLÜCK Burgergrill & Bar',
                lat: 48.120391845703125,
                lon: 11.602923393249512,
                repinned: true,
                address_1: 'St.-Martin-Straße 57',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1501244830000,
                name: 'Tech_Hub München',
                id: 25186228,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Tech_Hub-Munchen',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Tech_Hub-Munchen/events/268602441/',
            description: '<p>Join our IT-Job-Shuttle to the digital economy of Munich. During the tour, you can look behind the scenes of high-tech companies and have valuable contacts to IT-professionals of the participating companies. Catering will be provided all day. To the end of the day we have a Get-Together and serve good food and free beer.</p> <p>Steig ein in den IT-Job-Shuttle durch die Münchner Digitalwirtschaft. Während der mehrstündigen Tour kannst Du hinter die Kulissen von Hightech-Unternehmen schauen und wertvolle Kontakte zu Fachleuten und Personalern in den beteiligten Unternehmen knüpfen. Für die Verpflegung zwischendurch ist bestens gesorgt. Zum Ausklang des Abends erwarten Dich dann nochmal gutes Essen und Freibier.</p> <p>#hightech #kaffeefahrt #ITjobs</p> <p>Please REGISTER HERE <a href=\'https://www.eventbrite.de/e/hackjump-der-it-job-shuttle-in-munchen-2020-tickets-62571008571\' class=\'linkified\'>https://www.eventbrite.de/e/hackjump-der-it-job-shuttle-in-munchen-2020-tickets-62571008571</a></p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1522694856000,
            duration: 10800000,
            id: 'lkgknpybclblc',
            name: 'Deutsch-Japanischer\u00ad Stammtisch',
            rsvp_limit: 25,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1598634000000,
            local_date: '2020-08-28',
            local_time: '19:00',
            updated: 1597948632000,
            utc_offset: 7200000,
            waitlist_count: 2,
            yes_rsvp_count: 25,
            is_online_event: false,
            group: {
                created: 1512221367000,
                name: 'Deutsch-Japanischer Stammtisch',
                id: 26763059,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'deutsch-japanischer-stammtisch',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybclblc/',
            description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Im August treffen wir uns wieder im Biergarten. Der Veranstaltungsort wird Euch per persönlicher Nachricht in Meetup mitgeteilt. Im Biergarten machen wir keinen Vortrag.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1522694856000,
            duration: 10800000,
            id: 'lkgknpybcnbfc',
            name: 'Deutsch-Japanischer\u00ad Stammtisch',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1604080800000,
            local_date: '2020-10-30',
            local_time: '19:00',
            updated: 1593250869000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 2,
            is_online_event: false,
            group: {
                created: 1512221367000,
                name: 'Deutsch-Japanischer Stammtisch',
                id: 26763059,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'deutsch-japanischer-stammtisch',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcnbfc/',
            description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1597991874000,
            duration: 7200000,
            id: '272716693',
            name: 'F10 Online-Dojo (August20)',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1598619600000,
            local_date: '2020-08-28',
            local_time: '15:00',
            updated: 1597991874000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 3,
            venue: {
                id: 26906060,
                name: 'Online event',
                repinned: false,
                country: '',
                localized_country_name: ''
            },
            is_online_event: true,
            group: {
                created: 1551878701000,
                name: 'F10 Coding Dojo',
                id: 31321481,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'F10-Coding-Dojo',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/F10-Coding-Dojo/events/272716693/',
            description: '<p>Hallo zusammen,</p> <p>wir werden am Freitag, den 28.08 um 15 Uhr unser virtuelles Coding Dojo starten. Jeder von zu Hause und alles über BigBlueButton.<br/>Einwählen könnt ihr euch hier: <a href=\'https://bbb.faktorzehn.de/b/luk-3ng-rqx\' class=\'linkified\'>https://bbb.faktorzehn.de/b/luk-3ng-rqx</a></p> <p>The virtual coding dojo starts at 3 PM. Please log in via: <a href=\'https://bbb.faktorzehn.de/b/luk-3ng-rqx\' class=\'linkified\'>https://bbb.faktorzehn.de/b/luk-3ng-rqx</a></p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1579163487000,
            duration: 7200000,
            fee: {
                accepts: 'cash',
                amount: 42,
                currency: 'EUR',
                description: '',
                label: 'Price',
                required: false
            },
            id: '267957933',
            name: 'Agile Lean Munich 2020 – Der zweite ganztägige Open Space in München',
            rsvp_limit: 80,
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1605340800000,
            local_date: '2020-11-14',
            local_time: '09:00',
            rsvp_close_offset: 'PT24H',
            updated: 1588596438000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 39,
            venue: {
                id: 26082467,
                name: 'codecentric AG',
                lat: 48.12557601928711,
                lon: 11.610230445861816,
                repinned: true,
                address_1: 'August-Everding-Straße 20',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1552484914000,
                name: 'Agile Lean Munich',
                id: 31379982,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Agile-Lean-Munich',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Agile-Lean-Munich/events/267957933/',
            description: '<p>Der neue Termin für die ALM steht: 14. November 2020!</p> <p>Liebe Teilnehmenden und Interessierten der #agilen Community,<br/>nach Absprache mit @codecentric München, als Veranstaltungs-Ort-Geber haben wir einen neuen Termin für die zweite ALM am 14.November 2020 gefunden. Auch wenn es bis heute keine Planungssicherheit für die zweite Jahreshälfte gibt, hoffen wir, dass die Situation im November soweit stabil ist, dass wir die ALM guten Gewissens stattfinden lassen können.</p> <p>Die bisher gekauften Tickets behalten natürlich weiter ihre Gültigkeit.</p> <p>Wir hoffen auf eine stabile Situation bis November und freuen uns trotz aller Unsicherheiten auf einen tollen Tag mit Euch!</p> <p>Bleibt weiterhin gesund. Wir sehen uns (hoffentlich) im November!</p> <p>Euer ALM Orga-Team</p> <p>#almnov20 #almmai20 #scrum #kanban</p> <p>--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p> <p>⭐️Dieses Event ist kostenpflichtig (42€ p.P). Tickets erhaltet ihr über unsere Website www.agile-lean-munich.de ⭐️</p> <p>Wir wollen mit euch gemeinsam Themen rund um die agile Organisationsentwicklung besprechen.</p> <p>Agil ist längst nicht nur in der Softwareentwicklung das Mittel der Wahl, um Projekte für alle Beteiligten erfolgreicher durchzuführen. Agile ist eine neue Art zu arbeiten, die Transparenz, Selbstorganisation und Geschäftswert in den Vordergrund stellt und Teams und Unternehmen den Spaß an erfolgreicher Arbeit zurückgibt.</p> <p>Es geht um die Themen, die euch bewegen und die Erfahrungen, die ihr gemacht habt.</p> <p>Für die komplette Verpflegung des Tages (vom Frühstück über das Mittagessen bis zum Abschlussbier) wird gesorgt werden.</p> <p>Wir starten um 8:30 Uhr mit einem Frühstück und der Möglichkeit zum Netzwerken. Der Open Space beginnt um 09:30.</p> <p>Wir wünschen allen Teilnehmern viel Spaß!</p> ',
            how_to_find_us: 'Die Veranstaltung findet in den Räumen der codecentric AG statt',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1598251861000,
            duration: 10800000,
            id: '272775092',
            name: 'play board games',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1598799600000,
            local_date: '2020-08-30',
            local_time: '17:00',
            rsvp_open_offset: 'PT105H',
            updated: 1598251861000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            venue: {
                id: 26947718,
                name: 'Biergarten & Restaurant am Chinesischen Turm',
                lat: 48.151973724365234,
                lon: 11.592218399047852,
                repinned: false,
                address_1: 'Englischer Garten 3 ',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1493414929000,
                name: 'Munich Social Gaming',
                id: 23474017,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munich-Social-Gaming',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Munich-Social-Gaming/events/272775092/',
            description: '<p>Hi all,</p> <p>let\'s play our favorite games (Uno!, Coup, Dodelido, Saboteur) in a biergarten. Unlimited participants number! We rely on your help in bringing games if you have some. Looking forward to play with you!</p> <p>We will take tables near <a href=\'https://goo.gl/maps/Dsy1wayqRW1PCLEX9\' class=\'linkified\'>https://goo.gl/maps/Dsy1wayqRW1PCLEX9</a></p> <p>Cheers<br/>Evgeniy</p> ',
            how_to_find_us: 'see location pin, location link in description, go ahead to find a table with games and just let us know that you\'ve came to play with us!',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1585297132000,
            duration: 7200000,
            id: '269686692',
            name: 'Pitch Club Developer Edition #63',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1602698400000,
            local_date: '2020-10-14',
            local_time: '20:00',
            updated: 1585297132000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 2,
            venue: {
                id: 25959917,
                name: 'Bar Ludwig II',
                lat: 48.12186813354492,
                lon: 11.58230972290039,
                repinned: false,
                address_1: 'Hochstraße 77',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1539021073000,
                name: 'Pitch Club Developer Edition München',
                id: 30141555,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Pitch-Club-Developer-Edition-Munchen',
                who: 'Mitglieder',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Pitch-Club-Developer-Edition-Munchen/events/269686692/',
            description: '<p>Softwareentwickler und IT-Professionals aufgepasst! Pitch Club veranstaltet am 14. Oktober 2020 ab 17 Uhr in der Bar Ludwig II (Hochstraße 77, 81541 München) die “Pitch Club Developer Edition #63” in München. Hierfür suchen wir noch Entwickler und Projektmanager aus dem IT-Bereich, die an dem Event teilnehmen möchten.</p> <p>Beim Event treffen gestandene Unternehmen und Startups auf IT-Professionals, die es zu überzeugen gilt. Die Unternehmen pitchen ihr HR-Konzept, Jobs und Projekte und versuchen so, die Talente für sich zu gewinnen. Die Entwickler stellen zudem unbequeme Fragen und prüfen die Jobs auf Herz und Nieren. Am Ende müssen die Unternehmen in 1-on-1 Gesprächen nochmal alles geben, bei der alle Teilnehmer sich bei Speisen und Getränken austauschen und gegebenenfalls schon mit ihren zukünftigen Arbeitgebern in Kontakt treten können. Nach Abschluss der Veranstaltung geht das Event ab 20 Uhr in die öffentliche Afterwork Party über.</p> <p>Wenn Du an der kostenlosen Teilnahme (inklusive Snackbuffet, Softdrinks, Bier und Long Drinks) beim invite-only Event ab 17 Uhr interessiert bist, dann bewirb Dich unter: <a href=\'https://pcde.io/?q=m\' class=\'linkified\'>https://pcde.io/?q=m</a></p> <p>Wenn Du Interesse hast, an der anschließenden Afterwork ab 20 Uhr teilzunehmen, dann melde Dich einfach auf unserer Homepage unter <a href=\'https://pcde.io/pcde-afterwork/\' class=\'linkified\'>https://pcde.io/pcde-afterwork/</a> an.<br/>____________________________________________________________________________________</p> <p>Pitch Club is looking for Software Developers and IT-Professionals for its upcoming event “Pitch Club Developer Edition #63” on October 14th, 2020 starting at 5 p.m. at Bar Ludwig II (Hochstraße 77, 81541 Munich) in Munich.</p> <p>So this is like a job interview - but reversed! Companies and startups pitch themselves, the HR concepts, jobs and projects they offer to the audience, i.e. the Software Developers and IT-Professionals, who ask tough and hair-raising questions in addition. After the pitches you can get more information in 1-on-1 talks with the companies. All participants are invited to snacks, drinks and maybe you get to know your future employer. After the official part ends at 8 p.m., the event shifts over to the Afterwork Party, accessible for everyone.</p> <p>The participation for the official part as well as catering (including snacks, soft drinks, beverages &amp; long drinks) are for free! If you want to participate at the invite-only event, starting at 5 p.m., please apply via <a href=\'https://pcde.io/en/?q=m\' class=\'linkified\'>https://pcde.io/en/?q=m</a></p> <p>Please note: Most pitches will be held in German. Nonetheless, English-speaking developers are welcomed, too!</p> <p>If you are interested in taking part at the Afterwork Party, starting at 8 p.m., please register via <a href=\'https://pcde.io/en/pcde-afterwork/\' class=\'linkified\'>https://pcde.io/en/pcde-afterwork/</a></p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1595838909000,
            duration: 5400000,
            id: '272179649',
            name: 'FREE MEDITATION IN THE PARK',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1598549400000,
            local_date: '2020-08-27',
            local_time: '19:30',
            updated: 1595838909000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 12,
            venue: {
                id: 26931492,
                name: 'Park hinter St. Nikolai am Gasteig',
                lat: 48.133018493652344,
                lon: 11.590737342834473,
                repinned: true,
                address_1: 'Innere-Wiener-Str. 1',
                city: 'München',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1405527637000,
                name: 'Free Meditation & Yoga – in Munich/München (4.400+ members)',
                id: 15760412,
                join_mode: 'approval',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Free-Meditation-Yoga-Munich',
                who: 'Meditators',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Free-Meditation-Yoga-Munich/events/272179649/',
            description: '<p>Falls Ihr auch so richtig Lust auf eine Präsenz-Meditation an der frischen Luft habt - Dann kommt einfach in den Park neben dem Gasteig und meditiert mit uns!</p> <p>GELEITETE SAHAJA YOGA MEDITATION für Anfänger &amp; Fortgeschrittene</p> <p>EINTRITT FREI !</p> <p>THEMEN:<br/>- Aktivierung der Kundalini-Energie und Selbstverwirklichung<br/>- Reinigung der Basis-Chakren durch die Unterstützung von Mutter Erde<br/>- Vertiefung der Gedankenstille<br/>- Sahaj Wissen über die Chakren, Nadis und Kundalini</p> <p>ANMELDUNG:<br/>Beschränkte Teilnehmerzahl: Mit Anmeldung: Whatsapp:[masked] oder [masked]</p> <p>WO: Park hinter St. Nikolai am Gasteig, Innere-Wiener-Str. 1, S-Bahn Rosenheimerplatz, Tram 17 \'Gasteig\'</p> <p>BEI SCHLECHTWETTER:<br/>...meditieren wir im Sahaja Yoga Zentrum, nur 250m entfernt: Am Lilienberg 2a, 81699 München (gegenüber Gasteig)</p> <p>Wir meditieren auf der Wiese, bitte Decke, Matte oder Klappstuhl zum Sitzen mitnehmen.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1578988979000,
            duration: 10800000,
            id: '267900623',
            name: 'München OutSystems Meetup - Save the date!',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1605114000000,
            local_date: '2020-11-11',
            local_time: '18:00',
            updated: 1578988979000,
            utc_offset: 3600000,
            waitlist_count: 0,
            yes_rsvp_count: 1,
            is_online_event: false,
            group: {
                created: 1560928375000,
                name: 'Offizielle OutSystems München Meetup Gruppe',
                id: 32208133,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Munchen-OutSystems-Community',
                who: 'Members',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Munchen-OutSystems-Community/events/267900623/',
            description: '<p>Mehr Information wird in Kürze veröffentlicht.</p> ',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1595862058000,
            duration: 7200000,
            id: '272184643',
            name: 'Die Evolution des Marketings - und was das für Unternehmen bedeutet!',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1602176400000,
            local_date: '2020-10-08',
            local_time: '19:00',
            updated: 1598276527000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 15,
            venue: {
                id: 26906060,
                name: 'Online event',
                repinned: false,
                country: '',
                localized_country_name: ''
            },
            is_online_event: true,
            group: {
                created: 1473932394000,
                name: 'Rosenheimer New Work Meetup',
                id: 20428133,
                join_mode: 'open',
                lat: 47.86000061035156,
                lon: 12.149999618530273,
                urlname: 'Rosenheimer-New-Work-Meetup',
                who: 'Mitglieder',
                localized_location: 'Rosenheim, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Rosenheimer-New-Work-Meetup/events/272184643/',
            description: '<p>Das Marketing hat sich in den letzten 20 Jahren massiv verändert. Immer mehr Marketing-Aktivitäten werden in den digitalen Raum verlagert. Immer mehr Budget fließt aus traditionellen Kanälen ab ins Online-Marketing. Aber auch das Online-Marketing hat sich in den letzten 20 Jahren extrem entwickelt und verändert. Es wird immer granularer. Immer mehr Kanäle - und damit Marketing-Optionen kommen hinzu. Es fällt immer schwerer, den Überblick zu behalten und den \'optimalen\' Marketing-Mix zu entwickeln.</p> <p>In seinem Vortrag berichtet Dr. Erwin Lammenett von seinen Erfahrungen der letzten 25 Jahre. Sein Vortrag ist ein Mix aus ZDF (Zahlen, Daten, Fakten) und Anekdoten aus 25 Jahren Konzeptions- und Projektarbeit im digitalen Business.</p> <p>Schlussendlich beleuchtet Lammenett auch Fragen wie:<br/>- Was müssen Unternehmen tun, um trotz des ständigen Wandels nicht den Anschluss zu verlieren?<br/>- Wie könnte die Zukunft aussehen?<br/>- Und was bedeutet das für Unternehmen?</p> <p>Referent<br/>Dr. Erwin Lammenett ist Marketing-Problemlöser, entwickelt zielorientierte Konzepte für seine Kunden und berät sie strategisch.</p> <p>Seit 1995 ist er im Digital-Business. Damit ist er ein Internet-Kenner der ersten Stunde und verfügt mit mehr als 25 Jahren Berufspraxis über einen Erfahrungsschatz wie kaum ein anderer deutscher Berater. Seine Marketing-Bücher sind Bestseller. „Praxiswissen Online-Marketing“ ist inzwischen sogar in der 7. Auflage erhältlich, hat sich zum Standardwerk entwickelt und zählt auf Springer-Link aktuell mit allen Auflagen mehr als 1 Million Downloads.</p> <p>Lammenetts Markenzeichen sind Klartext, Know-how und Ausdauer. Mit diesen Eigenschaften führt er nicht nur Kundenprojekte zum Erfolg, sondern auch persönliche Vorhaben: Im Juni 2001 beispielsweise nahm er sich vor, sein Gewicht stark zu reduzieren und deutlich fitter zu werden. Im August 2002 hatte er zwei Ironman-Wettbewerbe erfolgreich absolviert (3,8 km swim, 180 km bike, 42,2 run)[1].</p> <p>Kunden und Partner von Dr. Lammenett profitieren von seiner direkten, unkomplizierten und unmissverständlichen Kommunikation genauso wie von seiner Expertise, die tiefgehendes Fachwissen mit einem Vierteljahrhundert Erfahrung kombiniert.</p> ',
            how_to_find_us: 'https://us02web.zoom.us/j/82338893108?pwd=a0N3SlFLdWp4TUNPY0hvZWo0L1MwZz09',
            visibility: 'public',
            pro_is_email_shared: false,
            member_pay_fee: false
        },
        {
            created: 1597476124000,
            duration: 7200000,
            id: '272591460',
            name: 'Endlich wieder Socializing Dinner',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1599843600000,
            local_date: '2020-09-11',
            local_time: '19:00',
            updated: 1597476124000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 6,
            venue: {
                id: 26846459,
                name: 'togather ',
                lat: 48.137943267822266,
                lon: 11.543676376342773,
                repinned: true,
                address_1: 'Schwanthalerstraße 160',
                city: 'München ',
                country: 'DE',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1538836714000,
                name: 'Co-Dining: inspirierender Austausch u. Netzwerken beim Essen',
                id: 30090989,
                join_mode: 'open',
                lat: 48.13999938964844,
                lon: 11.579999923706055,
                urlname: 'Co-Dining',
                who: 'Netzwerkerinnen und Netzwerker',
                localized_location: 'München, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Co-Dining/events/272591460/',
            description: '<p>Ausgehen, neue Leute Kennenlernen und feiern. Wir haben es alle lange gemisst.</p> <p>Am Freitagabend ist es endlich soweit wir wollen uns wieder treffen. Gutes Essen genießen und ein geselliges Miteinander erleben. Wer dabei sein möchte bitte anmelden.</p> <p>WAS DICH ERWARTET:<br/>Ich bin Gastgeberin aus Leidenschaft und glaube, dass wir zusammen mehr erreichen können. Zu diesem Zweck habe ich das togather Anfang des Jahres eröffnet.</p> <p>Wünscht du dir in einer Wohlfühlatmosphäre genussvoll und in Muße speisen zu können?</p> <p>Willst du dich in einem geselligen Rahmen mit Gleichgesinnten austauschen und dein soziales wie berufliches Netzwerk erweitern?</p> <p>Im togather lernst du neue interessante Menschen kennen, führst vielseitige Gespräche und gehst anschließend beschwingt und motiviert in deinen Tag zurück. Du gewinnst Lebensqualität durch liebevoll zubereitetes Essen in gemütlicher Atmosphäre.</p> <p>Klingt das gut? Dann bis Freitag!</p> ',
            how_to_find_us: 'am großen Community Table in der Restaurant Mitte',
            visibility: 'public',
            member_pay_fee: false
        },
        {
            created: 1597146335000,
            duration: 7200000,
            id: '272503456',
            name: '18. Usability Testessen - Remote',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1599753600000,
            local_date: '2020-09-10',
            local_time: '18:00',
            updated: 1597146355000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 3,
            venue: {
                id: 26906060,
                name: 'Online event',
                repinned: false,
                country: '',
                localized_country_name: ''
            },
            is_online_event: true,
            group: {
                created: 1473932394000,
                name: 'Rosenheimer New Work Meetup',
                id: 20428133,
                join_mode: 'open',
                lat: 47.86000061035156,
                lon: 12.149999618530273,
                urlname: 'Rosenheimer-New-Work-Meetup',
                who: 'Mitglieder',
                localized_location: 'Rosenheim, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Rosenheimer-New-Work-Meetup/events/272503456/',
            description: '<p>+++BEACHTE+++Aufgrund der begrenzten Plätze ist zur kostenlosen Teilnahme eine vorherige und verbindliche Anmeldung unter <a href=\'https://usability-testessen.org/stadt/region-rosenheim/\' class=\'linkified\'>https://usability-testessen.org/stadt/region-rosenheim/</a> notwendig.+++</p> <p>Liebe Testessen-Community,</p> <p>wir möchten euch weiterhin die Möglichkeit bieten eure Prototypen, Websites o. ä. auf ihre Gebrauchstauglichkeit zu testen. Weil es das letzte Mal schon so gut remote geklappt hat, haben wir uns dazu entschieden, das nächste Usability Testessen nochmal auf ein Webmeeting (ZOOM) zu verlagern!</p> <p>Damit das Verhältnis von Testpersonen und Testobjekten passt, werden wir die Anmeldebestätigungen inklusive Zugangsdaten zum ZOOM Meeting manuell versenden. Wer etwas zum Testen mitbringt, hat eine höhere Wahrscheinlichkeit einen Platz zu ergattern. Wer keine Bestätigung von uns erhält, steht automatisch auf der Warteliste und wird – sobald ein Platz frei wird – von uns informiert.</p> <p>+++++++++++++++++++++++++++++++++++++++++++++</p> <p>Seit Juni 2016 veranstalten wir das Usability-Testessen im Südostbayerischen Raum (Rosenheim und Umland). Die bisherige Resonanz ist extrem positiv.</p> <p>Das Ganze funktioniert relativ simpel, die Resultate sind häufig aber umso erstaunlicher: In einer Art Speed-Dating, stellen Unternehmen Ihre Webseite, Ihren Online-Shop, Ihre Software o.ä. mit konkreten Fragestellungen Testpersonen vor, die das Ganze dann testen und ehrliches und transparentes Feedback zur Bedienbarkeit (Usability) geben.</p> <p>Mehr Infos dazu gibt´s unter <a href=\'https://www.techdivision.com/blog/erstes-usability-testessen-in-sued-ost-bayern/\' class=\'linkified\'>https://www.techdivision.com/blog/erstes-usability-testessen-in-sued-ost-bayern/</a></p> <p>Am Donnerstag,[masked] findet das nächste Usability-Testessen statt.<br/>Sowohl für Testgeber als auch Tester ist das Ganze absolut kostenlos und unverbindlich. Beginn der Veranstaltung ist dieses Mal um 18 Uhr.</p> <p>Jetzt anmelden und echtes User-Feedback einholen!<br/><a href=\'https://usability-testessen.org/stadt/region-rosenheim/\' class=\'linkified\'>https://usability-testessen.org/stadt/region-rosenheim/</a></p> ',
            visibility: 'public',
            pro_is_email_shared: false,
            member_pay_fee: false
        },
        {
            created: 1595074456000,
            duration: 5400000,
            id: '272002824',
            name: 'Von einem, der auszog, den Wertstrom zu entdecken ...',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1600362000000,
            local_date: '2020-09-17',
            local_time: '19:00',
            updated: 1595074663000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 12,
            venue: {
                id: 26906060,
                name: 'Online event',
                repinned: false,
                country: '',
                localized_country_name: ''
            },
            is_online_event: true,
            group: {
                created: 1473932394000,
                name: 'Rosenheimer New Work Meetup',
                id: 20428133,
                join_mode: 'open',
                lat: 47.86000061035156,
                lon: 12.149999618530273,
                urlname: 'Rosenheimer-New-Work-Meetup',
                who: 'Mitglieder',
                localized_location: 'Rosenheim, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/Rosenheimer-New-Work-Meetup/events/272002824/',
            description: '<p>Wir freuen uns enorm, dass wir für unser New Work Meetup den bekannten Coach, Trainer, Berater und Autor Torsten Scheller gewinnen konnten, der über das spannende und top-aktuelle Thema der Wertstrom-Organisation sprechen wird.</p> <p>Funktionierende Teams allein reichen nicht, denn viele funktionierende Teams führen zu … vielen lokalen Optima. Warum eigentlich? Warum führen viele funktionierende Teams nicht zu seiner funktionierenden Organisation? Woran scheitern auch agile Organisationen? Wie müssen Organisationen aufgestellt sein, damit die Leistung der Organisation wirklich den Kunden begeistert?</p> <p>Diese Fragen führten Torsten zu einer Reise durch den trockenen Kontinent der Organisationslehre mit seiner Wüste namens „Die Taylor-Ford-Organisation“, vorbei an der Quelle „Wertschöpfung“ zum Delta des reißenden Wertstroms. Das Ergebnis seiner Reise sind Erkenntnisse (in Form eines Buches). Einen Einblick dazu möchte er Euch an diesem Abend geben.</p> <p>Inhalt: Von Organisatorischen Schulden über die beiden Grundprobleme heutiger Organisationen über Wertströme zur Struktur einer wertstrombasierten Organisation.</p> <p>Nutzen:</p> <p>- Ihr habt ein tieferes Verständnis davon, woran Organisation wirklich leiden.</p> <p>- Ihr versteht Wertschöpfung – und wie man diese organisieren muss – besser.</p> <p>- Ihr habt eine Idee davon, wie eine wertstrombasierte Organisation aussehen kann.</p> <p>Über Torsten Scheller<br/>Sein Ziel sind Rahmenbedingungen, in denen Menschen ihr Potenzial zum Nutzen aller entfalten. Funktionierende Organisationen sind ein erster Schritt zur Verwicklung seiner Vision: „Wir RENNEN am Morgen FREUDIG zu unserer Arbeit und ENTFALTEN KOOPERATIV unser Potenzial, um unsere KUNDEN mit herausragenden innovativen Produkten und Services ZU BEGEISTERN.“</p> ',
            how_to_find_us: 'https://us02web.zoom.us/j/84661011605?pwd=aGd5SFZ4OHJFSGVYaHBhNEszbFdaQT09',
            visibility: 'public',
            pro_is_email_shared: false,
            member_pay_fee: false
        },
        {
            created: 1589204082000,
            duration: 10800000,
            id: '270583071',
            name: 'GZDN Workshop  Go to Market: Kundenzentriert zu Traktion',
            date_in_series_pattern: false,
            status: 'upcoming',
            time: 1600779600000,
            local_date: '2020-09-22',
            local_time: '15:00',
            updated: 1593152235000,
            utc_offset: 7200000,
            waitlist_count: 0,
            yes_rsvp_count: 9,
            venue: {
                id: 26940742,
                name: 'LINK Gründerzentrum',
                lat: 48.55257797241211,
                lon: 12.187517166137695,
                repinned: false,
                address_1: 'Kiem-Pauli-Straße 8',
                city: 'Landshut',
                country: 'de',
                localized_country_name: 'Germany'
            },
            is_online_event: false,
            group: {
                created: 1426009776000,
                name: 'LINK-Das Gründerzentrum Landshut',
                id: 18491662,
                join_mode: 'open',
                lat: 48.540000915527344,
                lon: 12.140000343322754,
                urlname: 'LINKWORK',
                who: 'LINKWORKer',
                localized_location: 'Landshut, Germany',
                state: '',
                country: 'de',
                region: 'en_US',
                timezone: 'Europe/Berlin'
            },
            link: 'https://www.meetup.com/LINKWORK/events/270583071/',
            description: '<p>Wie Du wirklich funktionierende Kundenbeziehungen erreichst</p> <p>Unternehmen verlieren durch externe Marktvorgänge oder interne Unternehmensentwicklungen das Verständnis für den Kunden. Dabei werden langfristige Kundenbeziehungen als „gegeben“ angesehen. Dies ist fatal und wirkt sich auf Marketing, Vertrieb sowiedie Produktgenese aus.</p> <p>Wir entschlüsseln Kundenbedarfe durch Customer Development und geben daraus Impulse für Marketing, Sales und die Produktentwicklung. Sparekünftigmessbar an Kundenakquise-Kosten (CAC) bei gleichzeitigem Steigerndes Kundenwertes (LTV).</p> <p>Mögliche Anwendungsfälle:<br/>•Markteintritte und Produktlaunches schärfen<br/>•CRM Hürden und Chancen identifizieren<br/>•Kundenzentrierte Produktentwicklung</p> <p>Zielmarkt&amp; Zielpersonen<br/>Geschäftsführer, Marketing-und Produkt-Entscheider in Mittelstandsunternehmen im B2B Umfeld(Umsatz/Jahr&gt; 5Mio. €), welche die digitale Transformation als Chance für ihren Unternehmenserfolg begreifen. Gründer und Geschäftsführer finanzierter Startups oder Scale-ups im B2B Umfeld, die in kürzester Zeit explosiv wachsen wollen bzw. müssen.</p> <p>Referenten: André Wehr und Manuel Schmidt (Gründer tractionwise)</p> <p>Anmeldung bitter per Email an info(at)link-landshut.de.</p> ',
            visibility: 'public',
            member_pay_fee: false
        }
    ]
};

export { mockEvents };